################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    sections:
    - title: Before You Start
      link: docs/gettingstarted/getting-started.md
      - title: New Clients Before You Start
      link: docs/gettingstarted/getting-started-when-new.md
      - title: Exisiting Clients Before You Start
      link: docs/gettingstarted/getting-started-when-migerating.md
    - title: Access Tokens
      link: docs/gettingstarted/access-tokens.md
    - title: API Security
      link: docs/gettingstarted/api_security.md
    - title: Certificates
      link: docs/gettingstarted/certificates.md
    - title: Company Administrator
      link: docs/gettingstarted/company-administrator.md
    - title: Company Developer
      link: docs/gettingstarted/company-developer.md
    - title: Environments
      link: docs/gettingstarted/environments.md
    - title: Manage Developers
      link: docs/gettingstarted/manage-developers.md
    - title: Registration
      link: docs/gettingstarted/registration.md
    - title: Validate APIs in Sandbox
      link: docs/gettingstarted/validate-apis-in-sandbox.md
- sections:
  - title: Account
    sections:
  - title: Account Overview
    link: docs/release-notes/account/account-overview.md
  - title: Account Sandbox
    link: docs/release-notes/account/account-sandbox.md
- sections:
  - title: Card
    sections:
    - title: Card Overview
      link: docs/release-notes/card/card_overview.md
    - title: Card Sandbox
      link: docs/release-notes/card/card_sandbox.md
- sections:
  - title: Company
    sections:
    - title: Company Overview
      link: docs/release-notes/company/company-overview.md
    - title: Company Sandbox
      link: docs/release-notes/company/company-sandbox.md
- sections:
  - title: Dispute
    sections:
    - title: Dispute Overview
      link: docs/release-notes/dispute/dispute-overview.md
    - title: Dispute Sandbox
      link: docs/release-notes/dispute/dispute-sandbox.md
- sections:
  - title: Fraud
    sections:
    - title: Fraud Overview
      link: docs/release-notes/fraud/fraud_overview.md
    - title: Fraud Sandbox
      link: docs/release-notes/fraud/new-fraud-sandbox.md
- sections:
  - title: Payments
    sections:
    - title: Payment Overview
      link: docs/release-notes/payments/payments-overview.md
    - title: Payment Sandbox
      link: docs/release-notes/payments/payments-sandbox.md
- sections:
  - title: Reward
    sections:
    - title: uChoose® Overview
      link: docs/release-notes/reward/reward_overview.md
    - title: Reward Sandbox
      link: docs/release-notes/reward/reward_sandbox.md
- sections:
  - title: Webhook
    sections:
    - title: Webhook Overview
      link: docs/release-notes/webhook/webhook-overview.md
- sections:
  - title: Webhook Event Streaming
    sections:
    - title: Webhook Events
      link: docs/webhook/section-header.md
    - title: Card Activation
      link: docs/webhook/cardactivation-1.0.0.md
    - title: Card Add
      link: docs/webhook/cardadd-1.0.0.md
    - title: Card Address
      link: docs/webhook/cardaddress-1.0.0.md
    - title: Card Contact Info
      link: docs/webhook/cardcontactinfo-1.0.0.md
    - title: Card Dispute
      link: docs/webhook/carddispute-1.0.0.md
    - title: Card Expiration Date
      link: docs/webhook/cardexpirationdate-1.0.0.md
    - title: Cardholder Info
      link: docs/webhook/cardholderinfo-1.0.0.md
    - title: Card Limits
      link: docs/webhook/cardlimits-1.0.0.md
    - title: Card Pin Offset
      link: docs/webhook/cardpinoffset-1.0.0.md
    - title: Card Reissue
      link: docs/webhook/cardreissue-1.0.0.md
    - title: Card Security Info
      link: docs/webhook/cardsecurityinfo-1.0.0.md
    - title: Card Requested
      link: docs/webhook/cardshipping-1.0.0.md
    - title: Card Status
      link: docs/webhook/cardstatus-1.0.0.md
    - title: Prior Card Logic
      link: docs/webhook/priorcardlogic-1.0.0.md
- sections:
  - title: Release Notes
    sections:
    - title: Account
      link: docs/release-notes/account/account-release-note.md
    - title: Card
      link: docs/release-notes/card/card-release-note.md
    - title: Company
      link: docs/release-notes/company/company-release-note.md
    - title: Dispute
      link: docs/release-notes/dispute/dispute-release-note.md
    - title: Fraud
      link: docs/release-notes/fraud/fraud-release-note.md
    - title: Payment
      link: docs/release-notes/payments/payment-release-note.md
    - title: Reward
      link: docs/release-notes/reward/reward-release-note.md
    - title: Webhook
      link: docs/release-notes/webhook/webhook-release-note.md 
- sections:
  - title: FAQ    
    link: docs/faq/faq.md 
- sections:
  - title: Support    
    link: docs/getting-help-using-client360.md
- sections:
  - title: Contact Us    
    link: docs/contact-us.md

