################################################################################

# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates.

# Fiserv is a trademark of Fiserv, Inc.,

# registered or used in the United States and foreign countries,

# and may or may not be registered in your country.

# All trademarks, service marks,

# and trade names referenced in this

# material are the property of their

# respective owners. This work, including its contents

# and programming, is confidential and its use

# is strictly limited. This work is furnished only

# for use by duly authorized licensees of Fiserv, Inc.

# or its affiliates, and their designated agents

# or employees responsible for installation or

# operation of the products. Any other use,

# duplication, or dissemination without the

# prior written consent of Fiserv, Inc.

# or its affiliates is strictly prohibited.

# Except as specified by the agreement under

# which the materials are furnished, Fiserv, Inc.

# and its affiliates do not accept any liabilities

# with respect to the information contained herein

# and are not responsible for any direct, indirect,

# special, consequential or exemplary damages

# resulting from the use of this information.

# No warranties, either express or implied,

# are granted or extended by this work or

# the delivery of this work

################################################################################

- sections:
  - title: Getting Started
    sections:
    - title: Before You Start
      link: docs/gettingstarted/getting-started.md
    - title: New Clients Before You Start
      link: docs/gettingstarted/getting-started-when-new.md
    - title: Existing Clients Before You Start
      link: docs/gettingstarted/getting-started-when-migerating.md
    - title: Access Tokens
      link: docs/gettingstarted/access-tokens.md
    - title: API Security
      link: docs/gettingstarted/api_security.md
    - title: Certificates
      link: docs/gettingstarted/certificates.md
    - title: Company Administrator
      link: docs/gettingstarted/company-administrator.md
    - title: Company Developer
      link: docs/gettingstarted/company-developer.md
    - title: Environments
      link: docs/gettingstarted/environments.md
    - title: Manage Developers
      link: docs/gettingstarted/manage-developers.md
    - title: Registration
      link: docs/gettingstarted/registration.md
    - title: Validate APIs in Sandbox
      link: docs/gettingstarted/validate-apis-in-sandbox.md
- sections:
  - title: Account
    sections:
    - title: Account Overview
      link: docs/release-notes/account/account-overview.md
    - title: Account Sandbox
      sections:
      - title: Details
        link: docs/release-notes/account/Statements/accounts-details-sandbox.md
      - title: Limits
        link: docs/release-notes/account/Statements/account-limits-sandbox.md
      - title: Statements
        link: docs/release-notes/account/Statements/account-statements-sandbox.md
      - title: Transactions
        link: docs/release-notes/account/Statements/account-transaction-sandbox.md
- sections:
  - title: Card
    sections:
    - title: Card Overview
      link: docs/release-notes/card/card_overview.md
    - title: Card Sandbox
      sections:
      - title: Activations
        link: docs/release-notes/card/card-activation-sandbox.md
      - title: Add
        link: docs/release-notes/card/card-add-sandbox.md
      - title: Audit
        link: docs/release-notes/card/card-audit-sandbox.md
      - title: Compromised Card
        link: docs/release-notes/card/card-compromised-card-sandbox.md
      - title: Demographics
        link: docs/release-notes/card/card-demographics-sandbox.md
      - title: Details
        link: docs/release-notes/card/card-details-sandbox.md
      - title: Display Digital Card
        link: docs/release-notes/card/card-display-digital-card-sandbox.md
      - title: Limits
        link: docs/release-notes/card/card-limits-sandbox.md
      - title: Order
        link: docs/release-notes/card/card-order-sandbox.md
      - title: PIN
        link: docs/release-notes/card/card-pin-sandbox.md
      - title: Related Accounts
        link: docs/release-notes/card/card-related-accounts-sandbox.md
      - title: Replacement
        link: docs/release-notes/card/card-replacement-sandbox.md
      - title: Transactions
        link: docs/release-notes/card/card-transactions-sandbox.md
      - title: Update Status
        link: docs/release-notes/card/card-update-status-sandbox.md
  - title: Company
    sections:
    - title: Company Overview
      link: docs/release-notes/company/company-overview.md
    - title: Company Sandbox
      sections:
      - title: Company Accounts
        link: docs/release-notes/company/company-accounts-sandbox.md
      - title: Company Demographics
        link: docs/release-notes/company/company-demographics-sandbox.md
      - title: Company Details
        link: docs/release-notes/company/company-details-sandbox.md
      - title: Company Notes and Memo
        link: docs/release-notes/company/company-notes-sandbox.md
- sections:
  - title: Dispute
    sections:
    - title: Dispute Overview
      link: docs/release-notes/dispute/dispute-overview.md
    - title: Dispute Sandbox
      sections:
      - title: Dispute Create
        link: docs/release-notes/dispute/dispute-create-sandbox.md
      - title: Dispute Details
        link: docs/release-notes/dispute/dispute-details-sandbox.md
      - title: Dispute Update
        link: docs/release-notes/dispute/dispute-update-sandbox.md
- sections:
  - title: Fraud
    sections:
    - title: Fraud Overview
      link: docs/release-notes/fraud/fraud_overview.md
    - title: Fraud Sandbox
      sections:
      - title: Fraud Alerts
        link: docs/release-notes/fraud/fraud-alerts-sandbox.md
      - title: Fraud Case
        link: docs/release-notes/fraud/fraud-case-sandbox.md
      - title: Fraud Exemption
        link: docs/release-notes/fraud/fraud-exemption-sandbox.md
      - title: Fraud Travel Exemption
        link: docs/release-notes/fraud/fraud-travel-exemptions-sandbox.md
      - title: Fraud Verification
        link: docs/release-notes/fraud/fraud-verification-sandbox.md
- sections:
  - title: Payments
    sections:
    - title: Payment Overview
      link: docs/release-notes/payments/payments-overview.md
    - title: Payment Sandbox
      sections:
      - title: Payment Search
        link: docs/release-notes/payments/payments-search-sandbox.md
      - title: Payment Actions
        link: docs/release-notes/payments/payment-actions-sandbox.md
      - title: Payment Hold
        link: docs/release-notes/payments/payment-hold-sandbox.md
- sections:
  - title: Reward
    sections:
    - title: uChoose® Overview
      link: docs/release-notes/reward/reward_overview.md
    - title: Reward Sandbox
      link: docs/release-notes/reward/reward_sandbox.md
- sections:
  - title: Webhook
    sections:
    - title: Overview
      link: docs/release-notes/webhook/webhooks-Overview.md
    - title: Card activation
      link: docs/release-notes/webhook/cardactivation-1.0.0.md
    - title: Card add
      link: docs/release-notes/webhook/cardadd-1.0.0.md
    - title: Card address
      link: docs/release-notes/webhook/cardaddress-1.0.0.md
    - title: Card contact info
      link: docs/release-notes/webhook/cardcontactinfo-1.0.0.md
    - title: Card dispute
      link: docs/release-notes/webhook/carddispute-1.0.0.md
    - title: Card expiration date
      link: docs/release-notes/webhook/cardexpirationdate-1.0.0.md
    - title: Card holder info
      link: docs/release-notes/webhook/cardholderinfo-1.0.0.md
    - title: Card limits
      link: docs/release-notes/webhook/cardlimits-1.0.0.md
    - title: Card pin offset
      link: docs/release-notes/webhook/cardpinoffset-1.0.0.md
    - title: Card reissue
      link: docs/release-notes/webhook/cardreissue-1.0.0.md
    - title: Card security info
      link: docs/release-notes/webhook/cardsecurityinfo-1.0.0.md
    - title: Card shipping
      link: docs/release-notes/webhook/cardshipping-1.0.0.md
    - title: Card status
      link: docs/release-notes/webhook/cardstatus-1.0.0.md
    - title: Webhook prior card logic
      link: docs/release-notes/webhook/priorcardlogic-1.0.0.md
- sections:
  - title: Release Notes
    sections:
    - title: Account
      link: docs/release-notes/account/account-release-note.md
    - title: Card
      link: docs/release-notes/card/card-release-note.md
    - title: Company
      link: docs/release-notes/company/company-release-note.md
    - title: Dispute
      link: docs/release-notes/dispute/dispute-release-note.md
    - title: Fraud
      link: docs/release-notes/fraud/fraud-release-note.md
    - title: Payment
      link: docs/release-notes/payments/payment-release-note.md
    - title: Reward
      link: docs/release-notes/reward/reward-release-note.md
    - title: Webhook
      link: docs/release-notes/webhook/webhook-release-note.md
- sections:
  - title: FAQ  
    link: docs/faq/faq.md
- sections:
  - title: Support  
    link: docs/getting-help-using-client360.md
- sections:
  - title: Contact Us  
    link: docs/contact-us.md
