################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/gettingstarted/getting-started.md
    sections:
    - title: API Portal for Card Developers
      link: docs/gettingstarted/getting-started.md
    - title: API Security
      link: docs/gettingstarted/api_security.md
    - title: Access Tokens
      link: docs/gettingstarted/access-tokens.md
    - title: Certificates
      link: docs/gettingstarted/certificates.md
    - title: Company Administrator
      link: docs/gettingstarted/company-administrator.md
    - title: Company Developer
      link: docs/gettingstarted/company-developer.md
    - title: Environments
      link: docs/gettingstarted/environments.md
    - title: Registration
      link: docs/gettingstarted/registration.md
    - title: Validate APIs in Sandbox
      link: docs/gettingstarted/validate-apis-in-sandbox.md
- sections:
  - title: Account
    sections:
    - title: Account Overview
      link: docs/product/account_overview.md
    - title: Account Sandbox
      link: docs/release-notes/account/account_sandbox.md
- sections:
  - title: Card
    sections:
    - title: Card Overview
      link: docs/release-notes/card/card_overview.md
    - title: Card Sandbox
      link: docs/release-notes/card/card_sandbox.md
- sections:
  - title: Fraud
    sections:
    - title: Fraud Overview
      link: docs/release-notes/fraud/fraud_overview.md
    - title: Fraud Sandbox
      link: docs/release-notes/fraud/fraud_sandbox.md
- sections:
  - title: Reward
    sections:
    - title: uChoose® Overview
      link: docs/release-notes/reward/reward_overview.md
    - title: Reward Sandbox
      link: docs/release-notes/reward/reward_sandbox.md
