################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  #productName: REPLACEME
  productionDescription: Fiserv helps you harness the power of APIs specific to card services to spur innovation while remaining digitally relevant. We provide easy access to API functionality and help you create more favorable, intelligent, and secure consumer experiences. APIs from Fiserv provide a modern, intuitive and scalable service designed to give you a strategic business advantage.
  whoIsItFor: REPLACEME
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: REPLACEME™
featuredFeatures:
  - title: Account
    description:  Account API enables a financial institution or an account holder to maintain and retrieve information such as statements, details, balance and interest information.
    tags: []
    bullets: []  
    relatedDocs:
      - relatedDoc: 
        title: Retrieve Account Information
        description: View account-specific data as well as account-oriented information including transfer information, rates and balances.
        link: ./docs/REPLACE-ME1.md
      - relatedDoc: 
        title: Access Statements
        description: View statement information along with transactions and manage statement options.
        link: ./docs/REPLACE-ME2.md
      - relatedDoc: 
        title: Manage Account Details
        description: Update account information such as limits, accountholder information and billing information.
        link: ./docs/REPLACE-ME3.md
  - title: Card
    description:  Card API enables a financial institution or cardholder to manage and maintain their card information through various touchpoints.
    tags: []
    bullets: []  
    relatedDocs:
      - relatedDoc: 
        title: Manage
        description: Retrieve and update the status and reason codes for a debit card.
        link: ./docs/REPLACE-ME1.md
      - relatedDoc: 
        title: Security
        description: Increased touchpoints to deactivate or re-activate a card, increasing fraud mitigation.
        link: ./docs/REPLACE-ME2.md
      - relatedDoc: 
        title: Access Card Details
        description: Retrieve the card number, expiration date and CVV in real time.
        link: ./docs/REPLACE-ME3.md
