################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

header:
  productDescription: Fiserv helps you harness the power of APIs specific to card services to spur innovation while remaining digitally relevant. We provide easy access to API functionality and help you create more favorable, intelligent, and secure consumer experiences. APIs from Fiserv provide a modern, intuitive and scalable service designed to give you a strategic business advantage.
getStarted: docs/gettingstarted/getting-started.md
benefits:
  - title: Security
    description: Increased touchpoints to deactivate or re-activate a card, increasing fraud mitigation.
  - title: Convenient Experience
    description: Empower cardholders to manage exemptions as well and quickly respond to fraud notifications.
  - title: Reduce Operational Expenses
    description: Reduce time allocated to dispute servicing by eliminating “swivel chair” process.
guides:
  - title: API Security
    description: Details on transport and application layer security protecting API transactions.
    link: docs/gettingstarted/api_security.md
featuredFeatures:
  - title: Account
    groupName: API Domains
    featured: true
    description: Account API enables a financial institution or account holder to manage and maintain their account information through various touchpoints.
    relatedDocs:
      - link: docs/product/account_overview.md
        title: API Portal for Card Developers
    relatedAPIs:
      - type: post
        path: /v1/accounts/statements/search
        title: Account Details
  - title: Card
    groupName: API Domains
    featured: true
    description: Card API enables a financial institution or cardholder to manage and maintain their card information through various touchpoints.
    relatedDocs:
      - link: docs/gettingstarted/getting-started.md#api-portal-for-card-developers
        title: API Portal for Card Developers
    relatedAPIs:
      - type: put
        path: /v1/cards/activations
        title: Activation
  - name: Dispute
    groupName: API Domains
    featured: false
    description: Dispute API enables users to manage dispute cases for multiple or a single transaction.
    relatedDocs:
      - link: docs/gettingstarted/getting-started.md#api-portal-for-card-developers
        title: API Portal for Card Developers
    relatedAPIs:
      - type: post
        path: /payments/v1/charges
        title: link to API Explorer
  - name: Fraud
    groupName: API Domains
    featured: false
    description: Fraud API enables a financial institution or cardholder to manage, mitigate fraud losses and create travel exemptions while minimizing friction for the consumer.
    relatedDocs:
      - link: docs/gettingstarted/getting-started.md#api-portal-for-card-developers
        title: API Portal for Card Developers
    relatedAPIs:
      - type: post
        path: /payments/v1/charges
        title: link to API Explorer
  - title: Reward
    groupName: API Domains
    featured: true
    description: uChoose Rewards® from Fiserv helps financial institutions (FIs) boost their card activation and increases use rates by enabling cardholders to earn points across accounts and redeem them for valuable rewards like cash back, gift cards, merchandise, events, activities and travel.
    relatedDocs:
      - link: docs/gettingstarted/getting-started.md#api-portal-for-card-developers
        title: API Portal for Card Developers
    relatedAPIs:
      - type: post
        path: /v1/addpoints
        title: Reward Add Points
  - name: Tokenization
    groupName: Guides
    featured: false
    description: Transaction data is protected by a randomly-generated identifier known as a "token".
    relatedDocs:
      - link: docs/gettingstarted/getting-started.md#api-portal-for-card-developers
        title: API Portal for Card Developers
    relatedAPIs:
      - type: post
        path: /payments-vas/v1/tokens
        title: link to API Explorer
  - name: Verifications
    groupName: Guides
    featured: false
    description: Confirm account validity and provide notification.
    relatedDocs:
      - link: docs/gettingstarted/getting-started.md#api-portal-for-card-developers
        title: API Portal for Card Developers
    relatedAPIs:
      - type: post
        path: /payments-vas/v1/accounts/verification
        title: link to API Explorer
