################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: Fiserv helps you harness the power of APIs specific to card services to spur innovation while remaining digitally relevant. We provide easy access to API functionality and help you create more favorable, intelligent, and secure consumer experiences. APIs from Fiserv provide a modern, intuitive and scalable service designed to give you a strategic business advantage.
  whoIsItFor: Developers seeking to create apps and integrate them to Fiserv banking solutions.   
steps:  
  learnSteps:
    - title: Learn
      description: >
        Use the Fiserv Developer Studio to discover your next integration project. Developers can explore the APIs in our intelligent API Explorer.
      link:
  buildSteps:
    - title: Build
      description: >
        Leverage our sample code to get your application coded quickly. Developers can employ our Sandbox environment to create robust solutions.
      link:
  validateSteps:
    - title: Validate
      description: >
        Test your application end-to-end in our latest Sandbox environment. Use our state-of-the-art features to make your application more robust.
      link:
  deploySteps:
    - title: deploy
      description: >
        When your application is ready for deployment, submit it for our automated certification. Once certified, it can be deployed to the production.
      link:
featuredFeatures:
  - title: Card
    description: Card API enables a financial institution or cardholder to manage and maintain their card information through various touchpoints.
    tags: ["tag1", "tag2"]
    bullets: ["Faster acceptance than credit or debit", "Biometric security", "Global offering and acceptance"]
    #links: ["docs/fintechs/accountholder.md"]
    relatedDocs:
      - relatedDoc: 
        title: API Portal for Card Developers 
        description: A company of any type or size can offer company-branded digital applications that embed the range of services and capabilities presented by Fiserv using the Fiserv APIs.  The end user customer can create, update, and control the financial services provided by Fiserv, but the user experience belongs to your company.  It is your application powered by Fiserv.
        link: "docs/getting-started/before-you-start.md"
      - relatedDoc: 
        title: Card Developer Portal 
        description: The API Portal for Card Developers, also known as the Card Developer Portal, provides the information you need to use the Fiserv APIs,  Click APIs to access deep technical information for each API.
        link: "docs/getting-started/make-your-first-api-call.md"
      - relatedDoc: 
        title: Validation Environment
        description: The sandbox environment is the developer external testing ground. Clients can mimic the production environment and create simulated responses based on test cases and data from Fiserv. The sandbox environment is identical to production but points to a simulated API environment for API responses.
        link: "docs/response-codes.md"
    relatedAPIs:
      - relatedAPI: 
        title: Activation 
        description: Feature helps clients empower their cardholders to quickly activate cards online, through online mobile banking or other channels or directly with a representative. Expanding activation channels and improving digital touchpoints supports card adoption and use.
        type: "put"        
        path: "/v1/cards/activations"
      - relatedAPI: 
        title: Details
        description: Feature provides for searches to retrieve basic cardholder information using full card number or other details such as email address, last name and phone. The service enables entities that do not store and maintain sensitive card information, such as digital providers needing data for use with other card APIs, to gain access to basic cardholder information based on commonly known information.
        type: "post"        
        path: "/v1/cardholders/search"
      - relatedAPI: 
        title: Digital Card Display
        description: Feature provides consumers the ability to digitally display card details prior to receiving their physical plastic or the need arises for an established card.​ Consumers can immediately retrieve card number, expiration date and CVV to immediately perform ecommerce transactions.
        type: "post"        
        path: "/v1/cards/authDetails"
  - title: Account
    description: Account API enables users to maintain and retrieve information about accounts within their financial institution such as statements, details, balance and interest information.
    tags: ["tag1", "tag2"]
    bullets: ["Faster acceptance than credit or debit", "Biometric security", "Global offering and acceptance"]
    #links: ["/docs/?path=docs/fintechs/accountholder.md"]
    relatedDocs:
      - relatedDoc: 
        title: API Portal for Card Developers 
        description: A company of any type or size can offer company-branded digital applications that embed the range of services and capabilities presented by Fiserv using the Fiserv APIs.  The end user customer can create, update, and control the financial services provided by Fiserv, but the user experience belongs to your company.  It is your application powered by Fiserv.
        link: "docs/getting-started/before-you-start.md"
      - relatedDoc: 
        title: Card Developer Portal 
        description: The API Portal for Card Developers, also known as the Card Developer Portal, provides the information you need to use the Fiserv APIs,  Click APIs to access deep technical information for each API.
        link: "docs/getting-started/make-your-first-api-call.md"
      - relatedDoc: 
        title: Validation Environment
        description: The sandbox environment is the developer external testing ground. Clients can mimic the production environment and create simulated responses based on test cases and data from Fiserv. The sandbox environment is identical to production but points to a simulated API environment for API responses.
        link: "docs/response-codes.md"
    relatedAPIs:
      - relatedAPI: 
        title: Account Details
        description: Feature enables entities to pull basic and detailed account data for integration within consumer-facing or representative-facing channels to improve customer servicing.
        type: "post"        
        path: "/v1/accounts/statements/search"
      - relatedAPI: 
        title: View Statements
        description: Feature provides information about all billing statements available for the account. Detailed statement information provides all the individual transactions billed on a statement.
        type: "post"        
        path: "/v1/accounts/statements/search"
      - relatedAPI: 
        title: Update Account
        description: Modifies account-related information, such as deposit account details, interest payment details, flex data details, account address and name details.
        type: "post"        
        path: "/v1/accounts/statements/search"
  - title: Fraud
    description: Fraud API enables a financial institution or cardholder to manage, mitigate fraud losses and create travel exemptions while minimizing friction for the consumer.
    tags: ["tag1", "tag2"]
    bullets: ["Faster acceptance than credit or debit", "Biometric security", "Global offering and acceptance"]
    #links: ["/docs/?path=docs/fintechs/accountholder.md"]
    relatedDocs:
      - relatedDoc: 
        title: API Portal for Card Developers 
        description: A company of any type or size can offer company-branded digital applications that embed the range of services and capabilities presented by Fiserv using the Fiserv APIs.  The end user customer can create, update, and control the financial services provided by Fiserv, but the user experience belongs to your company.  It is your application powered by Fiserv.
        link: "docs/getting-started/before-you-start.md"
      - relatedDoc: 
        title: Card Developer Portal 
        description: The API Portal for Card Developers, also known as the Card Developer Portal, provides the information you need to use the Fiserv APIs,  Click APIs to access deep technical information for each API.
        link: "docs/getting-started/make-your-first-api-call.md"
      - relatedDoc: 
        title: Validation Environment
        description: The sandbox environment is the developer external testing ground. Clients can mimic the production environment and create simulated responses based on test cases and data from Fiserv. The sandbox environment is identical to production but points to a simulated API environment for API responses.
        link: "docs/response-codes.md"
    relatedAPIs:
      - relatedAPI: 
        title: Fraud Case Search
        description: Provides integration partners the ability to receive alerts for potential fraudulent transactions, retrieve case data for fraudulent cases, and notify Fiserv of the results of an alert notification.
        type: "put"        
        path: "/v1/case/search"
      - relatedAPI: 
        title: Alert Outcomes
        description: Enables collection and application of all travel exemptions for a specific card number. Any cardholder updates are captured and used by other web services in the authorization rules for each card transaction, reducing false declines and giving users more control over how they use their card.
        type: "put"        
        path: "/v1/alertOutcome"
      - relatedAPI: 
        title: Fraud Case Close
        description: Feature will provide the ability to manage a case by way of retrieving detailed case information and viewing case comments..
        type: "put"        
        path: "/v1/caseClose"
benefits:
  - title: Market Reach
    description: >
      Pre-integrate your app to Fiserv platforms used by more than one in three financial institutions in the U.S. Reach 100 million digital banking users.
  - title: Simplified Integration.
    description: >
      More than 25,000 fields from Fiserv banking solutions are exposed through normalized APIs, enabling once-and-done integration. No point-to-point integration to individual platforms.
  - title: Co-Innovation
    description: >
      Collaborate with financial institutions to create highly personalized touchpoints and customer journeys.
featuredAPIs:
  - name: Charges
    description: Used to submit a charge transaction.
    type: POST
    route: /payments/v1/charges
    codeSample: '[json
                  {
                     "amount":{
                        "total":"12.04",
                        "currency":"USD"
                     },
                     "source":{
                        "sourceType":"PaymentCard",
                        "card":{
                           "cardData":"4005550000000019",
                           "expirationMonth":"02",
                           "expirationYear":"2035",
                           "securityCode":"123",
                           "securityCodeIndicator":"PROVIDED"
                        }
                     },
                     "transactionDetails":{
                        "captureFlag":true
                     }
                  }]'
    language: Curl
    link: link to API Explorer
  - name: Tokenization
    description: Transaction data is protected by a randomly-generated identifier known as a "token".
    type: POST
    route: /payments-vas/v1/tokens
    codeSample: '[json
                  {
                     "amount":{
                        "total":"1.00",
                        "currency":"USD"
                     },
                     "source":{
                        "sourceType":"PaymentCard",
                        "card":{
                           "cardData":"4005550000000019",
                           "expirationMonth":"02",
                           "expirationYear":"2035",
                           "securityCode":"123"
                        }
                     },
                     "transactionDetails":{
                        "captureFlag":false,
                        "createToken":true,
                        "tokenProvider":"RSA"
                     }
                  }]'
    language: Curl
    link: link to API Explorer 
  - name: Verifications
    description: Confirm account validity and provide notification.
    type: POST
    route: /payments-vas/v1/accounts/verification
    codeSample: '[json
                  {
                     "source":{
                        "sourceType":"PaymentCard",
                        "card":{
                           "cardData":"4005550000000019",
                           "expirationMonth":"02",
                           "expirationYear":"2035"
                        }
                     }
                  }]'
    language: Curl
    link: link to API Explorer  
  - name: Capture
    description: Capture pending authorization for settlement post authorization.
    type: POST
    route: /payments/v1/charges/{transactionId}/capture
    codeSample: '[json
                  {
                    "amount": {
                      "total": "12.04",
                      "currency": "USD"
                    },
                    "transactionDetails": {
                      "captureFlag": true
                    }
                  }]'
    language: Curl
    link: link to API Explorer   
useCases:
  - title: Enterprise Cards-Based Disbursements
    subtitle: 
    description: > 
      Partner with financial institutions to serve companies that require cards-based disbursements for insurance claims payments, merchant rebates, loyalty rewards, employee bonuses, expense reimbursements, loan payouts, refunds and so forth.
    link: docs/getting-started.md
  - title: Affinity Card Marketing
    subtitle: 
    description: > 
      Partner with financial institutions to offer cards that appeal to unique constituencies. 
    link: docs/getting-started.md