---
openapi: 3.0.0
info:
  description: API to generate Access Token (OAuth 2.0 bearer token).
  version: 1.0.1
  title: Access Token
servers:
  - url: https://card.api.fiservapps.com/cs/oauth2
    description: Production server (uses live data)
  - url: https://card-sandbox.api.fiservapps.com/cs/oauth2
    description: Sandbox server (uses test data)
tags:
- name: Token
schemes:
- https
security:
- basicAuth: []
paths:
  /v1/token:
    post:
      tags:
      - Token
      summary: API to generate an access token.
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: scope
        in: query
        description: Required. Specifies the access available to the client application after it is authenticated.
        required: true
        type: string
        example: /cs/api
      - name: accept
        in: header
        description: Identifies the media format that clients accepts.
        required: false
        type: string
      - name: content-type
        in: header
        description: Required. Identifies the type of the payload (for POST and PUT operations) that the client is sending. It should be the same as what the server is expecting.
        required: true
        type: string
      - name: authorization
        in: header
        description: "Required. Authenticates the user and the system. Enter the app Key:Secret, separated by a colon, encoded in Base64 format. \nFormat basic [Base64 encoded (Key:Secret)]\nFind the API Key and API Secret from your Developer App (Keys tab) in the Card Developer Portal. The keys are app-specific and can have subscription to one or more Fiserv API products."
        required: true
        type: string
      - name: x-fapi-financial-id
        in: header
        description: 8 digit unique financial institute id assigned to each FI by Fiserv. If your application is serving multiple clients then x-fapi-financial-id signifies the financial institute id of FI your application is sending request for.
        required: true
        type: number
      - name: x-fapi-interaction-id
        in: header
        description: Optional. Represents a transaction identification (transaction ID) value for tracking purposes. This field is optional in the request but always returned in the response. If a value is provided in the request, the same will be sent back in the response. Otherwise, a Fiserv-generated ID is added to the response.
        required: false
        type: string
        maxLength: 40
        minLength: 15
        pattern: ^[^-][a-zA-Z0-9-][^-]$
      - in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/tokenRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokenResponse'
        "400":
          description: Bad Request
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 400
                description: missing header x-fapi-financial-id
        "401":
          description: Unauthorized access
          schema:
            type: object
            example:
              errors:
              - code: 401
                description: Invalid ApiKey
        "404":
          description: Resource Not Found
        "415":
          description: Unsupported Media Type
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 415
                description: unsupported Media Type
        "429":
          description: Too Many Requests
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 429
                description: Rate limit quota violation. Quota limit  exceeded.
        "500":
          description: Server Error
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errorResponse:
                code: 500-01
                message: internal server error
                developerInfo:
                  developerMessage: internal server error
                  moreInfo: There was a problem handling your request.  Please try again.  If the problem persists please contact Fiserv ETSD at 888-243-2543 (you unique messageID included below)
                  messageid: 25557-84290371-1
      security:
      - basicAuth: []
securityDefinitions:
  basicAuth:
    type: basic
definitions:
  tokenRequest:
    type: object
    properties:
      grant_type:
        type: string
        example: client_credentials
        description: Required. The method for granting access to resources.
  tokenResponse:
    type: object
    properties:
      token_type:
        type: string
        example: BearerToken
      issued_at:
        type: string
        format: utc-millisec
        example: "1603444768597"
      api_key:
        type: string
        example: bDq9pIrpLj04aTfvAI9dsjVZQhiAE3kL
      access_token:
        type: string
        example: CgXcGWgN5azrUyGgCBjOBgdNfj0n
      expires_in:
        type: string
        format: utc-millisec
        example: "899"
        description: "Access Token is valid for 15 minutes (900 milliseconds)"
