---
swagger: "2.0"
info:
  description: This API helps user/account holder to get the SSO(Single-sign-on) URL. The destination URL field gives the link for the single sign on and brings to the U-Choose Rewards Page.
  version: 1.0.2
  title: uChoose Rewards Single Sign On API
host: card.api.fiservapps.com
basePath: /cs/uChooseRewards
schemes:
- https
security:
- BearerToken: []
paths:
  /v1/sso-url:
    post:
      tags:
      - Rewards
      summary: Return a URL link to the participant for a Single Sign On (SSO) session to the Rewards website.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: x-fapi-financial-id
        in: header
        description: Required. Enter the client id.
        required: true
        type: string
        maxLength: 8
        minLength: 1
        pattern: ^[0-9]*$
      - name: x-fapi-interaction-id
        in: header
        description: Enter the transaction/correlation id
        required: false
        type: string
        maxLength: 40
        minLength: 15
        pattern: ^[^-][a-zA-Z0-9-][^-]$
      - name: Authorization
        in: header
        description: 'Enter ''Bearer '' followed by the access token. Please refer to documentation on bearer token. '
        required: true
        type: string
      - in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/GetSSORequest'
      responses:
        "200":
          description: Successful
          headers:
            x-fapi-interaction-id:
              type: string
              description: Represents a transaction ID created with each request.
          schema:
            $ref: '#/definitions/GetSSOResponse'
        "400":
          description: Bad Request
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 200/100
                description: User does not have the authority to view this data
        "401":
          description: Unauthorized access
          schema:
            type: object
            example:
              errors:
              - code: 401
                description: Invalid access token
        "404":
          description: Resource Not Found
        "415":
          description: Unsupported Media Type
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 415
                description: unsupported Media Type
        "429":
          description: Too Many Requests
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 429
                description: Rate limit quota violation. Quota limit  exceeded.
        "500":
          description: Server Error
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errorResponse:
                code: 500-01
                message: internal server error
                developerInfo:
                  developerMessage: internal server error
                  moreInfo: There was a problem handling your request.  Please try again.  If the problem persists please contact Fiserv ETSD at 888-243-2543 (you unique messageID included below)
                  messageid: 25557-84290371-1
securityDefinitions:
  BearerToken:
    description: Enter 'Bearer ' followed by the access token.
    type: apiKey
    name: Authorization
    in: header
definitions:
  GetSSORequest:
    type: object
    required:
    - client
    - rewardsKeyInfo
    properties:
      client:
        $ref: '#/definitions/Client'
      rewardsKeyInfo:
        $ref: '#/definitions/rewardsKeyInfo'
      email:
        type: string
        example: sandbox.app@fiserv.com
        description: Optional. If an email address is not provided in the initial request, cardholders will be required to manually enter an email the first time they access the Rewards website.
  GetSSOResponse:
    type: object
    properties:
      destURL:
        type: string
        example: '"https://uat.uchooserewards.com/members/ssoredirect.php?sid=21XXPqWyH842807&amp;xmembid=32398882&amp;redoip=y"'
        description: If an email address is not provided in the initial request, the URL example above prompts the participant to enter an email. If an email address was provided, a different URL is generated to enable navigation directly to the Rewards page.
  Client:
    type: object
    required:
    - applicationName
    - auditId
    - id
    - vendorName
    properties:
      id:
        type: string
        example: "11122203"
        description: Client organization Identifier
      applicationName:
        type: string
        example: CM
        description: Client application identifier
      vendorName:
        type: string
        example: ITI
        description: Client vendor identifier
      auditId:
        type: string
        example: "123456"
        description: 'AuditID identifies the entity on whose behalf the request is made.  This value often identifies a user.   '
        maxLength: 13
  rewardsKeyInfo:
    type: object
    required:
    - useMultiAuth
    properties:
      cardNumber:
        type: string
        example: "5004065676691"
        description: The participant card number. NOTE - Enter either card number, account number, or both.
        maxLength: 22
      accountNumber:
        type: string
        example: "3445454545"
        description: The primary Rewards account number. NOTE - Enter either account number, card number or both.
        maxLength: 22
      useMultiAuth:
        type: boolean
        example: false
        description: If true, the total points will include all multi-authed accounts.
